/**
 * This code was generated by Builder.io.
 */
import React from 'react';

export const Pagination: React.FC = () => {
  return (
    <div className="flex gap-5 self-end mt-20 text-base tracking-wider text-center text-neutral-400 max-md:mt-10">
      <div className="my-auto">
        1 <span className="text-neutral-400">2 3</span>
      </div>
      <img
        loading="lazy"
        sizes="(max-width: 638px) 4vw, (max-width: 998px) 3vw, 2vw"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8df4d1dec403068700d1852a7eac4659ea51588eac0cd390eb6265bb65737c54?apiKey=a87584e551b6472fa0f0a2eb10f2c0ff&width=24"
        className="shrink-0 w-6 aspect-square"
        alt="Next page"
      />
    </div>
  );
};