/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button } from "../ui/button";

interface PaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
}

export const Pagination: React.FC<PaginationProps> = ({
  currentPage,
  totalPages,
  onPageChange,
}) => {
  const handlePrevious = () => {
    if (currentPage > 1) {
      onPageChange(currentPage - 1);
    }
  };

  const handleNext = () => {
    if (currentPage < totalPages) {
      onPageChange(currentPage + 1);
    }
  };

  const renderPageNumbers = () => {
    const pages = [];
    const maxVisiblePages = 3;

    let startPage = Math.max(1, currentPage - Math.floor(maxVisiblePages / 2));
    let endPage = Math.min(totalPages, startPage + maxVisiblePages - 1);

    if (endPage - startPage + 1 < maxVisiblePages) {
      startPage = Math.max(1, endPage - maxVisiblePages + 1);
    }

    for (let i = startPage; i <= endPage; i++) {
      pages.push(
        <button
          key={i}
          onClick={() => onPageChange(i)}
          className={`px-2 py-1 transition-colors ${
            i === currentPage
              ? "text-black font-semibold"
              : "text-neutral-400 hover:text-black"
          }`}
        >
          {i}
        </button>,
      );
    }

    return pages;
  };

  if (totalPages <= 1) {
    return null;
  }

  return (
    <div className="flex gap-5 self-end mt-20 text-base tracking-wider text-center max-md:mt-10">
      <div className="flex items-center gap-2">{renderPageNumbers()}</div>
      <div className="flex gap-2">
        <Button
          variant="ghost"
          size="icon"
          onClick={handlePrevious}
          disabled={currentPage === 1}
          className="w-6 h-6 p-0 hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <img
            loading="lazy"
            sizes="(max-width: 638px) 4vw, (max-width: 998px) 3vw, 2vw"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8df4d1dec403068700d1852a7eac4659ea51588eac0cd390eb6265bb65737c54?apiKey=a87584e551b6472fa0f0a2eb10f2c0ff&width=24"
            className="w-4 h-4 rotate-180"
            alt="Previous page"
          />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          onClick={handleNext}
          disabled={currentPage === totalPages}
          className="w-6 h-6 p-0 hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <img
            loading="lazy"
            sizes="(max-width: 638px) 4vw, (max-width: 998px) 3vw, 2vw"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8df4d1dec403068700d1852a7eac4659ea51588eac0cd390eb6265bb65737c54?apiKey=a87584e551b6472fa0f0a2eb10f2c0ff&width=24"
            className="w-4 h-4"
            alt="Next page"
          />
        </Button>
      </div>
    </div>
  );
};
