/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { Button } from '@/components/ui/button';

interface ContentBlockProps {
  title: string;
  description: string;
  buttonText: string;
}

const ContentBlock: React.FC<ContentBlockProps> = ({
  title,
  description,
  buttonText
}) => {
  return (
    <div className="flex flex-col self-stretch my-auto min-w-[240px] w-[685px] max-md:max-w-full">
      <h2 className="text-2xl font-semibold text-black tracking-[5.25px] max-md:max-w-full">
        {title}
      </h2>
      <p className="mt-12 mr-12 text-lg text-black max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
        {description}
      </p>
      <Button variant="tertiary" className="self-start mt-12 max-md:mt-10">
        {buttonText}
      </Button>
    </div>
  );
};

export default ContentBlock;