/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import ContentBlock from './ContentBlock';

describe('ContentBlock', () => {
  const props = {
    title: 'Test Title',
    description: 'Test Description',
    buttonText: 'Test Button'
  };

  it('renders the component with correct props', () => {
    render(<ContentBlock {...props} />);

    expect(screen.getByText(props.title)).toBeInTheDocument();
    expect(screen.getByText(props.description)).toBeInTheDocument();
    expect(screen.getByText(props.buttonText)).toBeInTheDocument();
  });
});