/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import SustainabilitySection from './SustainabilitySection';

describe('SustainabilitySection', () => {
  const props = {
    title: 'OUR COMMITMENT TO SUSTAINABILITY',
    description: 'Wahoo fun',
    buttonText: 'LEARN MORE',
    imageSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/539b4f8a1dc54a9c6c0e64c7ab487c9ef0bdc85f02e5c8f4eb576a3124d4479a?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801',
    imageAlt: 'Sustainability image'
  };

  it('renders the component with correct props', () => {
    render(<SustainabilitySection {...props} />);

    expect(screen.getByText(props.title)).toBeInTheDocument();
    expect(screen.getByText(props.description)).toBeInTheDocument();
    expect(screen.getByText(props.buttonText)).toBeInTheDocument();
    expect(screen.getByAltText(props.imageAlt)).toBeInTheDocument();
  });
});