/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { Button } from '@/components/ui/button';
import ContentBlock from './ContentBlock';

interface SustainabilitySectionProps {
  title: string;
  description: string;
  buttonText: string;
  imageSrc: string;
  imageAlt: string;
}

const SustainabilitySection: React.FC<SustainabilitySectionProps> = ({
  title,
  description,
  buttonText,
  imageSrc,
  imageAlt
}) => {
  return (
    <section className="flex flex-wrap gap-10 justify-between items-center mt-36 w-full max-w-[1198px] max-md:mt-10 max-md:max-w-full">
      <ContentBlock
        title={title}
        description={description}
        buttonText={buttonText}
      />
      <img
        loading="lazy"
        src={imageSrc}
        alt={imageAlt}
        className="object-contain self-stretch my-auto rounded-lg aspect-[1.05] min-w-[240px] w-[470px] max-md:max-w-full"
      />
    </section>
  );
};

export default SustainabilitySection;