/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button } from '../ui/button'

type NavItemProps = {
  text: string;
  isHighlighted?: boolean;
};

const NavItem: React.FC<NavItemProps> = ({ text, isHighlighted }) => (
  <div className={isHighlighted ? "text-rose-500" : "text-white"}>{text}</div>
);

type SignInButtonProps = {
  text: string;
};

const SignInButton: React.FC<SignInButtonProps> = ({ text }) => (
  <Button variant="secondary" className="bg-white text-black">
    {text}
  </Button>
);

const MyComponent: React.FC = () => {
  const navItems = [
    "WOMEN",
    "MEN",
    "COLLECTIONS",
    "SHOP ALL",
    { text: "SALE", isHighlighted: true },
  ];

  return (
    <div className="flex justify-center items-center px-16 py-20 bg-neutral-800 max-md:px-5">
      <div className="flex flex-col mt-20 w-full max-w-[1209px] max-md:mt-10 max-md:max-w-full">
        <header className="flex gap-5 justify-between w-full text-base font-semibold tracking-[3.15px] max-md:flex-wrap max-md:max-w-full">
          <nav className="flex gap-5 justify-between my-auto max-md:flex-wrap">
            {navItems.map((item, index) =>
              typeof item === "string" ? (
                <NavItem key={index} text={item} />
              ) : (
                <NavItem key={index} text={item.text} isHighlighted={item.isHighlighted} />
              )
            )}
          </nav>
          <div className="flex gap-5 justify-between">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6047d6295230a128a9d162198c043ef85d502d52bc6f0442a5a1f76a401b7568?apiKey=a87584e551b6472fa0f0a2eb10f2c0ff&"
              className="shrink-0 my-auto w-4 aspect-[0.88]"
              alt=""
            />
            <SignInButton text="SIGN IN" />
          </div>
        </header>
        <p className="mt-8 text-lg text-zinc-400 max-md:max-w-full">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere erat a ante
          vestibulum, in volutpat ligula elementum.
        </p>
      </div>
    </div>
  );
};

export default MyComponent;