// app/layout.tsx
import { Inter } from 'next/font/google';
import { builder } from '@builder.io/sdk';
import './globals.css';
import { Metadata } from 'next';
import { PropsWithChildren, Suspense } from 'react';
import Navigation from '../components/navigation/navigation';
import { NavigationProps } from '../components/navigation/navigation';


// export const dynamic = 'force-static';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<div>Loading...</div>}>
          {/* <Navigation headerData={params} /> */}
        </Suspense>
        <main>{children}</main>
      </body>
    </html>
  );
}
