/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { styled } from '@linaria/react';

const SectionContainer = styled.section`
  display: flex;
  margin-top: 115px;
  flex-direction: column;
  align-items: center;
  justify-content: center;

  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
  }
`;

const SectionTitle = styled.h2`
  color: var(--color-primary, #000);
  text-align: center;
  letter-spacing: 5.25px;
  font: 600 25px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const CategoryGrid = styled.div`
  display: flex;
  margin-top: 63px;
  align-items: start;
  gap: 33px;
  color: var(--color-primary, #000);
  text-align: center;
  letter-spacing: 0.75px;
  justify-content: start;
  flex-wrap: wrap;
  font: 400 15px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
    white-space: initial;
  }
`;

const CategoryItem = styled.div`
  display: flex;
  min-width: 240px;
  flex-direction: column;
  align-items: center;
  justify-content: start;
  width: 278px;

  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const CategoryImage = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 278px;
  border-radius: 7px;
  max-width: 100%;
`;

const CategoryName = styled.p`
  margin-top: 31px;
`;

interface CategoryProps {
  name: string;
  imageSrc: string;
}

const categories: CategoryProps[] = [
  { name: 'Women', imageSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/83d424be1dd45ee25189396131b6ebaf5061531e806f9008355ac1721a8607d2?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801' },
  { name: 'Men', imageSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/83d424be1dd45ee25189396131b6ebaf5061531e806f9008355ac1721a8607d2?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801' },
  { name: 'Accessories', imageSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/83d424be1dd45ee25189396131b6ebaf5061531e806f9008355ac1721a8607d2?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801' },
  { name: 'Sale', imageSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/83d424be1dd45ee25189396131b6ebaf5061531e806f9008355ac1721a8607d2?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801' },
];

export const CategorySection: React.FC = () => {
  return (
    <SectionContainer>
      <SectionTitle>SHOP BY CATEGORY</SectionTitle>
      <CategoryGrid>
        {categories.map((category, index) => (
          <CategoryItem key={index}>
            <CategoryImage src={category.imageSrc} alt={`${category.name} category`} />
            <CategoryName>{category.name}</CategoryName>
          </CategoryItem>
        ))}
      </CategoryGrid>
    </SectionContainer>
  );
};