/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { styled } from '@linaria/react';

const SectionContainer = styled.section`
  justify-content: center;
  align-items: center;
  background: var(--color-background-light, #fafafa);
  background-color: var(--color-muted, #c8e2ee);
  align-self: stretch;
  display: flex;
  margin-top: 115px;
  min-height: 617px;
  width: 100%;
  flex-direction: column;
  padding: 99px 0;

  @media (max-width: 991px) {
    max-width: 100%;
    padding-bottom: 100px;
    margin-top: 40px;
  }
`;

const ContentWrapper = styled.div`
  display: flex;
  width: 1243px;
  max-width: 100%;
  flex-direction: column;
`;

const SectionTitle = styled.h2`
  color: var(--color-primary, #000);
  text-align: center;
  letter-spacing: 5.25px;
  align-self: center;
  font: 600 25px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const FeatureGrid = styled.div`
  display: flex;
  margin-top: 113px;
  align-items: start;
  gap: 40px 100px;
  justify-content: space-between;
  flex-wrap: wrap;

  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
  }
`;

const FeatureItem = styled.div`
  display: flex;
  min-width: 240px;
  min-height: 268px;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  width: 341px;
`;

const IconFrame = styled.div<{ bgColor: string }>`
  border-radius: 48px;
  background-color: ${props => props.bgColor};
  display: flex;
  min-height: 90px;
  min-width: 90px;
  width: 92px;
  align-items: center;
  gap: 10px;
  overflow: hidden;
  justify-content: center;
  height: 92px;
  padding: 0 15px;
`;

const FeatureIcon = styled.img`
  aspect-ratio: 0.89;
  object-fit: contain;
  object-position: center;
  width: 50px;
  align-self: stretch;
  margin: auto 0;
`;

const FeatureTitle = styled.h3`
  color: var(--color-primary, #000);
  text-align: center;
  letter-spacing: 3.78px;
  margin-top: 19px;
  font: 700 18px Poppins, sans-serif;
`;

const FeatureDescription = styled.p`
  color: var(--color-primary, #000);
  text-align: center;
  margin-top: 19px;
  font: 400 18px Poppins, sans-serif;
`;

interface FeatureProps {
  icon: string;
  title: string;
  description: string;
  bgColor: string;
}

const features: FeatureProps[] = [
  {
    icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/41111a299718787ef3e0c5f649a486325dd49d295f20c54537afd6c08da1c3f7?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801',
    title: '2-DAY SHIPPING',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere erat a ante vestibulum, in volutpat ligula elementum.',
    bgColor: 'rgba(200, 226, 238, 1)',
  },
  {
    icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/341efe7d39b86406eeb2ca4ba0b2aecc0a87a517e7d71b9dd1fb31b284ada482?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801',
    title: 'CARBON NEUTRAL',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere erat a ante vestibulum, in volutpat ligula elementum.',
    bgColor: 'rgba(200, 238, 206, 1)',
  },
  {
    icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/512cf8a3a3e1d7476262f5f817e8858aea72ce809d2f476ecf69c9ac0d869991?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801',
    title: 'ADVANCED DYE TECH',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere erat a ante vestibulum, in volutpat ligula elementum.',
    bgColor: 'rgba(212, 200, 238, 1)',
  },
];

export const FeatureSection: React.FC = () => {
  return (
    <SectionContainer>
      <ContentWrapper>
        <SectionTitle>WHAT'S DIFFERENT ABOUT SHOPAHOLIC</SectionTitle>
        <FeatureGrid>
          {features.map((feature, index) => (
            <FeatureItem key={index}>
              <IconFrame bgColor={feature.bgColor}>
                <FeatureIcon src={feature.icon} alt={`${feature.title} icon`} />
              </IconFrame>
              <FeatureTitle>{feature.title}</FeatureTitle>
              <FeatureDescription>{feature.description}</FeatureDescription>
            </FeatureItem>
          ))}
        </FeatureGrid>
      </ContentWrapper>
    </SectionContainer>
  );
};