/**
 * This code was generated by Builder.io.
 */
import { css } from '@linaria/core';

export const globalStyles = css`
  :global() {
    body {
      font-family: Poppins, sans-serif;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    .visually-hidden {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border: 0;
    }

    :root {
      --color-primary: #000;
      --color-secondary: #fff;
      --color-background-light: #fafafa;
      --color-muted: #c8e2ee;
    }
  }
`;