/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { styled } from '@linaria/react';
import { Button } from '@/components/Button';

const HeroContainer = styled.section`
  display: flex;
  flex-direction: column;
  border-radius: 7px;
  position: relative;
  min-height: 588px;
  width: 100%;
  max-width: 1200px;
  align-items: flex-end;
  padding: 240px 17px 240px 80px;

  @media (max-width: 991px) {
    max-width: 100%;
    padding: 100px 0 100px 20px;
  }
`;

const HeroImage = styled.img`
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
`;

const HeroTitle = styled.h1`
  position: relative;
  color: var(--color-secondary, #fff);
  letter-spacing: 7.14px;
  font: 600 34px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const ButtonWrapper = styled.div`
  position: relative;
  display: flex;
  width: 131px;
  max-width: 100%;
  flex-direction: column;
  justify-content: start;
  margin: 15px 20px -47px 0;

  @media (max-width: 991px) {
    margin: 0 10px 10px 0;
  }
`;

export const HeroSection: React.FC = () => {
  return (
    <HeroContainer>
      <HeroImage src="https://cdn.builder.io/api/v1/image/assets/TEMP/412e8232faf5c79b8722451ee53eb36d58d2da388875a3935d18ba5e7932af71?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801" alt="Essential accessories background" />
      <HeroTitle>ESSENTIAL ACCESSORIES</HeroTitle>
      <ButtonWrapper>
        <Button variant="secondary">SHOP NOW</Button>
      </ButtonWrapper>
    </HeroContainer>
  );
};