/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { styled } from '@linaria/react';
import { Button } from '@/components/Button';
import { Collection } from '@/components/Collection';
import { HeroSection } from './HeroSection';
import { SustainabilitySection } from './SustainabilitySection';
import { CategorySection } from './CategorySection';
import { FeatureSection } from './FeatureSection';

const PageContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const StyledHeading = styled.h2`
  color: var(--color-primary, #000);
  text-align: center;
  letter-spacing: 5.25px;
  font: 600 25px Poppins, sans-serif;
  margin-top: 89px;

  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const CarouselWrapper = styled.div`
  width: 1274px;
  max-width: 100%;
  margin: 68px 0 0 33px;

  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const ShopAllButton = styled(Button)`
  margin-top: 63px;

  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const ShopaholicPage: React.FC = () => {
  return (
    <PageContainer>
      <HeroSection />
      <StyledHeading>STEP INTO FRESH STYLES</StyledHeading>
      <CarouselWrapper>
        <Collection collection="all" />
      </CarouselWrapper>
      <SustainabilitySection />
      <CategorySection />
      <ShopAllButton variant="default">SHOP ALL</ShopAllButton>
      <FeatureSection />
    </PageContainer>
  );
};

export default ShopaholicPage;