/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { styled } from '@linaria/react';
import { Button } from '@/components/Button';

const SectionContainer = styled.section`
  display: flex;
  margin-top: 141px;
  width: 100%;
  max-width: 1198px;
  align-items: center;
  gap: 40px 43px;
  justify-content: space-between;
  flex-wrap: wrap;

  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
  }
`;

const LeftPanel = styled.div`
  align-self: stretch;
  display: flex;
  min-width: 240px;
  flex-direction: column;
  width: 685px;
  margin: auto 0;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const SectionTitle = styled.h2`
  color: var(--color-primary, #000);
  letter-spacing: 5.25px;
  font: 600 25px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const SectionDescription = styled.p`
  color: var(--color-primary, #000);
  margin: 46px 48px 0 0;
  font: 400 18px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
    margin: 40px 10px 0 0;
  }
`;

const LearnMoreButton = styled(Button)`
  align-self: start;
  margin-top: 46px;

  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const SustainabilityImage = styled.img`
  aspect-ratio: 1.05;
  object-fit: contain;
  object-position: center;
  width: 470px;
  border-radius: 7px;
  align-self: stretch;
  min-width: 240px;
  margin: auto 0;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

export const SustainabilitySection: React.FC = () => {
  return (
    <SectionContainer>
      <LeftPanel>
        <SectionTitle>OUR COMMITMENT TO SUSTAINABILITY</SectionTitle>
        <SectionDescription>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere erat a ante vestibulum, in volutpat ligula elementum. Mauris scelerisque, ex ac fringilla auctor, nulla erat tempus enim, vel tincidunt arcu turpis vel enim.
        </SectionDescription>
        <LearnMoreButton variant="tertiary">LEARN MORE</LearnMoreButton>
      </LeftPanel>
      <SustainabilityImage src="https://cdn.builder.io/api/v1/image/assets/TEMP/539b4f8a1dc54a9c6c0e64c7ab487c9ef0bdc85f02e5c8f4eb576a3124d4479a?placeholderIfAbsent=true&apiKey=f5348105e75441b59830f1e489577801" alt="Sustainability commitment illustration" />
    </SectionContainer>
  );
};