/**
 * This code was generated by Builder.io.
 */
export interface ButtonProps {
  variant: 'default' | 'secondary' | 'tertiary';
  children: React.ReactNode;
  className?: string;
}

export interface CollectionProps {
  collection: string;
  className?: string;
}