/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AccessoriesTitle from "./AccessoriesTitle";

const AccessoriesSection: React.FC = () => {
  return (
    <section className="accessories-section">
      <AccessoriesTitle title="ACCESORIOS ESENCIALES" />
    </section>
  );
};

export default AccessoriesSection;
