/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface AccessoriesTitleProps {
  title: string;
}

const AccessoriesTitle: React.FC<AccessoriesTitleProps> = ({ title }) => {
  return (
    <h2 className="relative text-4xl font-semibold text-white tracking-[7.14px] max-md:max-w-full">
      {title}
    </h2>
  );
};

export default AccessoriesTitle;
