/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import CategoryItem from './CategoryItem';

describe('CategoryItem', () => {
  const mockProps = {
    image: 'http://b.io/test-image',
    name: 'Test Category'
  };

  it('renders the image with correct src and alt text', () => {
    render(<CategoryItem {...mockProps} />);
    const image = screen.getByRole('img');
    expect(image).toHaveAttribute('src', mockProps.image);
    expect(image).toHaveAttribute('alt', 'Test Category category');
  });

  it('renders the category name', () => {
    render(<CategoryItem {...mockProps} />);
    expect(screen.getByText(mockProps.name)).toBeInTheDocument();
  });
});