/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface CategoryItemProps {
  image: string;
  name: string;
}

const CategoryItem: React.FC<CategoryItemProps> = ({ image, name }) => {
  return (
    <div className="flex overflow-hidden flex-col items-center whitespace-nowrap w-[16%]">
      <img loading="lazy" src={image} alt={`${name} category`} className="object-contain max-w-full aspect-[0.8] w-[218px]" />
      <div className="self-stretch mt-3 max-w-full underline w-[130px]">{name}</div>
    </div>
  );
};

export default CategoryItem;