/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import ShopByCategory from './ShopByCategory';

describe('ShopByCategory', () => {
  it('renders the component with correct title', () => {
    render(<ShopByCategory />);
    expect(screen.getByText('Shop By Category')).toBeInTheDocument();
  });

  it('renders all category items', () => {
    render(<ShopByCategory />);
    expect(screen.getAllByRole('img')).toHaveLength(6);
  });

  it('renders category names', () => {
    render(<ShopByCategory />);
    expect(screen.getByText('dresses')).toBeInTheDocument();
    expect(screen.getByText('Tops')).toBeInTheDocument();
    expect(screen.getByText('denim')).toBeInTheDocument();
    expect(screen.getByText('pants')).toBeInTheDocument();
    expect(screen.getByText('tees')).toBeInTheDocument();
    expect(screen.getByText('Shoes & Accessories')).toBeInTheDocument();
  });
});