/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Link from 'next/link';
import Image from 'next/image'
import { Button } from '../ui/button';

interface FullImageHeroProps {
  title: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  backgroundImage: string;
  alignment: 'left' | 'center' | 'right';
}

const FullImageHero: React.FC<FullImageHeroProps> = ({
  title,
  description,
  buttonText,
  buttonLink,
  backgroundImage,
  alignment,
}) => {
  const alignmentClasses = {
    left: 'items-start text-left',
    center: 'items-center text-center',
    right: 'items-end text-right',
  };

  return (
    <div className={`flex overflow-hidden relative flex-col justify-center ${alignmentClasses[alignment]} w-full min-h-[442px] max-md:pr-5 max-md:max-w-full`}>
      <Image
        loading="lazy"
        src={backgroundImage}
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <div className={`flex relative flex-col justify-center px-16 py-20 max-w-full w-2/3 max-md:px-5 ${alignmentClasses[alignment]}`}>
        <div className={`flex flex-col mt-8 mb-2.5 shadow-sm max-md:mr-1 max-md:max-w-full ${alignmentClasses[alignment]}`}>
          <div className="flex flex-col text-white max-md:max-w-full">
            <h1 className="text-5xl font-black leading-[52.8px] max-md:max-w-full">
              {title}
            </h1>
            <p className="mt-3 text-2xl leading-9 max-md:max-w-full">
              {description}
            </p>
          </div>
          <Button className="flex flex-col justify-center mt-8 max-w-full w-[134px]" variant="secondary" size="lg" asChild>
            <Link href={buttonLink}>{buttonText}</Link>
          </Button>
        </div>
      </div>
    </div>
  );
};

export default FullImageHero;