/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ColorFilterProps {
  selectedColors: string[];
  setSelectedColors: React.Dispatch<React.SetStateAction<string[]>>;
}

const colors = [
  { name: 'Soft Blue', bgColor: 'bg-[#5b6b7b]' },
  { name: 'Rose', bgColor: 'bg-[#7b5b5d]' },
  { name: 'Moss Green', bgColor: 'bg-[#637b5b]' },
  { name: 'Soft Grey', bgColor: 'bg-[#9b9b9b]' },
  { name: 'Powder', bgColor: 'bg-slate-300' },
  { name: 'Navy', bgColor: 'bg-blue-800' },
];

export const ColorFilter: React.FC<ColorFilterProps> = ({
  selectedColors,
  setSelectedColors,
}) => {
  const handleColorChange = (colorName: string) => {
    setSelectedColors((prev) =>
      prev.includes(colorName)
        ? prev.filter((c) => c !== colorName)
        : [...prev, colorName]
    );
  };

  return (
    <>
      <div className="flex flex-wrap gap-5 justify-center content-start mt-5 w-full whitespace-nowrap max-md:pr-5">
        {colors.map((color) => (
          <div
            key={color.name}
            className="flex flex-col justify-center items-center w-[29%] max-md:w-[44%] cursor-pointer"
            onClick={() => handleColorChange(color.name)}
          >
            <div
              className={`shrink-0 rounded-full ${color.bgColor} h-[50px] w-[50px] ${selectedColors.includes(color.name) ? 'ring-2 ring-offset-2 ring-black' : ''
                }`}
            />
            <div className="mt-4">{color.name}</div>
          </div>
        ))}
      </div>
    </>
  );
};