/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SizeFilterProps {
  selectedSizes: string[];
  setSelectedSizes: React.Dispatch<React.SetStateAction<string[]>>;
}

const sizes = Array.from({ length: 18 }, (_, i) => i.toString());
const sizeLabels = ['X SMALL', 'SMALL', 'MEDIUM', 'LARGE', 'X LARGE', 'XX LARGE'];

export const SizeFilter: React.FC<SizeFilterProps> = ({
  selectedSizes,
  setSelectedSizes,
}) => {
  const handleSizeChange = (size: string) => {
    setSelectedSizes((prev) =>
      prev.includes(size)
        ? prev.filter((s) => s !== size)
        : [...prev, size]
    );
  };

  return (
    <>
      <div className="box-border flex relative flex-col shrink-0 mt-4 bg-zinc-300 h-[5px]" />
      <div className="flex gap-5 justify-between mt-3.5 font-semibold whitespace-nowrap tracking-[2.25px]">
        <div className="my-auto">Size</div>
        <img
          loading="lazy"
          sizes="(max-width: 638px) 4vw, (max-width: 998px) 3vw, 2vw"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e30cc75c785fe59e1b12a7afa6196e8215f91dcee8a10ee8524131fc5c758170?apiKey=a87584e551b6472fa0f0a2eb10f2c0ff&width=24"
          className="shrink-0 w-6 aspect-square"
          alt="Size icon"
        />
      </div>
      <div className="flex flex-row flex-wrap gap-2.5 px-px mt-4 whitespace-nowrap">
        {sizes.map((size) => (
          <div
            key={size}
            className={`justify-center items-center p-2.5 bg-neutral-100 h-[50px] w-[50px] cursor-pointer ${
              selectedSizes.includes(size) ? 'bg-blue-500 text-white' : ''
            }`}
            onClick={() => handleSizeChange(size)}
          >
            {size}
          </div>
        ))}
      </div>
      <div className="box-border flex relative flex-row flex-wrap shrink-0 gap-2.5 justify-center items-center mt-2.5 text-xs">
        {sizeLabels.map((label) => (
          <div
            key={label}
            className={`flex-1 justify-center p-2.5 text-center bg-neutral-100 cursor-pointer ${
              selectedSizes.includes(label) ? 'bg-blue-500 text-white' : ''
            }`}
            onClick={() => handleSizeChange(label)}
          >
            {label}
          </div>
        ))}
      </div>
    </>
  );
};